[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'tests'
ffi = true
eth_rpc_url = 'https://sepolia.base.org'
fs_permissions = [{ access = 'read-write', path = '.' }]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Enable gas reporting
gas_reports = ["*"]
